version: 2
updates:
  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: monthly
  - package-ecosystem: 'bun'
    directory: '/'
    schedule:
      interval: 'monthly'
    allow:
      - dependency-name: '@ts-defold*'
