name: CI/CD

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.x

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Defold
        uses: dapetcu21/setup-defold@v3.0.3

      - name: Install Dependencies
        run: bun install

      - name: Genrate lua w/ ts-defold
        run: bun run build

      - name: Build
        run: 'java -jar $BOB --root ./app --archive --platform js-web --verbose resolve distclean build bundle'
